services:
  pyrogram_bridge:
    image: ghcr.io/vvzvlad/pyrogram-bridge:latest
    container_name: pyrogram-bridge
    environment:
      TG_API_ID: //TG_API_ID//
      TG_API_HASH: //TG_API_HASH//
      TG_SESSION_STRING: //TG_SESSION_STRING//
      TZ: Europe/Moscow
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s